export const signatures = [
    { handle: "satyanadella", location: "California, USA", message: "I love live share 2" },
    { handle: "scottgu", location: "California, USA", message: "I love live share 2" },
    { handle: "samjgeorge", location: "California, USA", message: "I love live share 2" },
    { handle: "lostintangent", location: "Washington, USA", message: "I love live share" },
    { handle: "amandaksilver", location: "Washington, USA", message: "I love live share" },
    { handle: "DonovanBrown", location: "Washington, USA", message: "I love live share" },
    { handle: "shanselman", location: "Washington, USA", message: "I love live share" },
    { handle: "chuxel", location: "Minnesota, USA",message: "I love live share 2" },
    { handle: "legomushroom", location: "California, USA", message: "I love live share 2" },
    { handle: "jonwchu", location: "California, USA", message: "I love live share 2" },
    { handle: "bradygaster", location: "California, USA", message: "I love live share 2" },
    { handle: "simcalv", location: "California, USA", message: "I love live share 2" },
    { handle: "davidkpiano", location: "California, USA", message: "I love live share 2" },
    { handle: "johnmont", location: "California, USA", message: "I love live share 2" },
    { handle: "chrisdias", location: "California, USA", message: "I love live share 2" },
    { handle: "nz_sean", location: "California, USA", message: "I love live share 2" },
    { handle: "erichgamma", location: "California, USA", message: "I love live share 2" },
    { handle: "pjmeyer", location: "California, USA", message: "I love live share 2" },
    { handle: "srivatsn", location: "California, USA", message: "I love live share 2" },
    { handle: "auchenberg", location: "California, USA", message: "I love live share 2" },
    { handle: "weinand", location: "California, USA", message: "I love live share 2" },
    { handle: "kaimaetzel", location: "California, USA", message: "I love live share 2" },
    { handle: "dougam", location: "California, USA", message: "I love live share 2" },
    { handle: "julwhite", location: "California, USA", message: "I love live share 2" },
    { handle: "kuhlenhuth", location: "California, USA", message: "I love live share 2" },
    { handle: "jeffhollan", location: "California, USA", message: "I love live share 2" },
    { handle: "andysterland", location: "California, USA", message: "I love live share 2" },
    { handle: "dhopton_ms", location: "California, USA", message: "I love live share 2" },
    { handle: "jlzander", location: "California, USA", message: "I love live share 2" },
    { handle: "markrussinovich", location: "California, USA", message: "I love live share 2" },
    { handle: "jsnover", location: "California, USA", message: "I love live share 2" },
    { handle: "gabrtv", location: "California, USA", message: "I love live share 2" },
    { handle: "brendandburns", location: "California, USA", message: "I love live share 2" },
    { handle: "julwhite", location: "California, USA", message: "I love live share 2" },
    { handle: "kuhlenhuth", location: "California, USA", message: "I love live share 2" },
    { handle: "jeffhollan", location: "California, USA", message: "I love live share 2" },
    { handle: "andysterland", location: "California, USA", message: "I love live share 2" },
    { handle: "dhopton_ms", location: "California, USA", message: "I love live share 2" },
    { handle: "jlzander", location: "California, USA", message: "I love live share 2" },
    { handle: "markrussinovich", location: "California, USA", message: "I love live share 2" },
    { handle: "jsnover", location: "California, USA", message: "I love live share 2" },
    { handle: "gabrtv", location: "California, USA", message: "I love live share 2" },
    { handle: "brendandburns", location: "California, USA", message: "I love live share 2" }
];